const ERROR_CODES = {
  BAD_REQUEST: -1,
  NOT_FOUND: -2,
  UNKNOWN: -3,

  TOO_MANY_REQUESTS: 9000,

  // User
  USER_NOT_FOUND: 1000,
  USER_EMAIL_OR_PASSWORD_INCORRECT: 1100,
  USER_ALREADY_EXISTS: 1200,

  // Task
  TASK_NOT_FOUND: 2000,
  TASK_ALREADY_EXISTS: 2100,

  // Auth
  NOT_AUTHORIZED: 3000,
  AUTHENTICATION_ERROR: 3100,
};

module.exports = { ERROR_CODES };
