const ERROR_CODES = {
  BAD_REQUEST: -1,
  NOT_FOUND: -2,
  UNKNOWN: -3,

  TOO_MANY_REQUESTS: 9000,

  // User
  USER_NOT_FOUND: 1000,
  USER_EMAIL_OR_PASSWORD_INCORRECT: 1100,
  USER_ALREADY_EXISTS: 1200,
};

module.exports = { ERROR_CODES };
